---
title: `Canada_N_footprint`
output: html_notebook
---

```{r libraries, echo=FALSE, message = FALSE}
library(readr)
library(readxl)
library(dplyr)
library(tidyr)

library(ggplot2)
library(RColorBrewer)
library(ggpubr)
library(forcats)
```

```{r Scoping, echo=FALSE, message = FALSE}
years = c(2017, 2018, 2019)

prov_code <- matrix(c(1, "Canada", 10, "Newfoundland Labrador", 11,	"Prince Edward Island", 12,	"Nova Scotia", 13, "New Brunswick", 24, "Quebec", 35, 	"Ontario", 46,	"Manitoba", 47, "Saskatchewan", 48, "Alberta", 59, "British Columbia"), ncol=2, byrow = TRUE)
colnames(prov_code) <- c("GEO_code", "GEO")
prov_code <- as_tibble(prov_code)
prov_code$GEO_code <- as.numeric(prov_code$GEO_code)

GEO <- factor(c("Canada", "British Columbia", "Alberta", "Saskatchewan", "Manitoba", "Ontario", "Quebec", "New Brunswick", "Nova Scotia", "PEI", "NFLD"), levels = c("Canada", "British Columbia", "Alberta", "Saskatchewan", "Manitoba", "Ontario", "Quebec", "New Brunswick", "Nova Scotia", "PEI", "NFLD"))

prov_pop <- read_csv("Data/Population/provincial_pop.csv", skip = 1)%>%
  separate(REF_DATE, sep="-", into=c("month", "year"))%>%
  filter(month == "Jan")%>%
  select(year, GEO, VALUE)%>%
  mutate(year = as.numeric(year))%>%
  filter(year %in% c(17, 18, 19))%>%
  group_by(GEO)%>%
  summarize(Population = mean(VALUE))
```

#Crop VNF
```{r crop_categorization, echo=FALSE, message = FALSE}
#Names from StatsCan Crop Surveys, with doubles/subcategories removed
field_crop_list = c("Barley", "Beans, all dry (white and coloured)", "Canary seed", "Canola (rapeseed)", "Chick peas", "Corn for grain", "Corn for silage", "Faba beans", "Flaxseed", "Lentils", "Rye, all", "Oats", "Soybeans", "Sugar beets", "Peas, dry", "Sunflower seed", "Tame hay", "Triticale", "Wheat, all")                                          
#removed subcategories/duplicates "Beans, dry white", "Beans, dry coloured", "Rye, all including fall rye remaining" "Rye, fall remaining" "Rye, spring" "Rye, fall seeded in previous fall" "Wheat, all including winter wheat remaining" "Wheat, durum" "Wheat, spring" "Wheat, Canada Western Extra Strong (CWES)" "Wheat, Canada Western Red Spring (CWRS)"  "Wheat, Canada Prairie Spring Red (CPSR) and Canada Prairie Spring White (CPSW)" "Wheat, Canada Western Soft White Spring (CWSWS)" "Wheat, other spring" "Wheat, winter remaining" "Wheat, winter seeded in fall" "Wheat, all excluding durum wheat""Wheat, Canada Western Special Purpose (CWSP)" "Wheat, Canada Western Hard White Spring (CWHWS)" "Wheat, Canada Northern Hard Red (CNHR)" "Wheat, Canada Eastern Red Spring (CERS)"
#removed "Borage seed" "Caraway seed" "Coriander seed" "Mustard seed" "Safflower" "Hemp", "Buckwheat" (no recommended fert rates or no longer reported)

fruit_list = c("apples", "blueberries", "grapes", "peaches", "pears", "plums and prune plums", "raspberries", "strawberries", "nectarines", "cranberries")
#removed subcategories/duplicates "highbush blueberries" "lowbush blueberries" "Labrusca grapes" "vinifera, fresh French hybrid grapes", 
#removed "saskatoon berries" only grown is saskatchewan, no apricots (under 100 ha), black berries, currants, haskap, cherries due to insufficient data

vegetable_survey_list = c("cabbage", "rutabagas and turnips", "beets", "cauliflowers", "sweet corn", "lettuce", "parsnips", "green and wax beans", "carrots", "cucumbers and fresh gherkins (all varieties)", "tomatoes", "green peas", "asparagus", "celery", "dry onions", "spinach", "peppers", "broccoli", "Brussels sprouts", "leeks", "pumpkins", "French shallots and green onions", "squash and zucchini")
#removed parsely, regular cabbage" "Chinese cabbage" "watermelons", 'sweet potatoes, rhubarb, radishes, asian radishes, kale, eggplant, garlic due to insufficient data  

#Food grouping lists
cereals_list = c("Corn for grain", "Rye, all", "Oats", "Triticale", "Wheat, all") #stuff that people eat crops with less than 60% livestock allocation based on Karimi et al 2020 (Table A4)

feed_list = c("Barley", "Corn for silage", "Wheat, all", "Soybeans", "Tame hay") #based on Sheppard

legume_list = c("Beans, all dry (white and coloured)", "Chick peas", "Lentils", "Soybeans", "Peas, dry")

oilseed_list = c("Canola (rapeseed)", "Sunflower seed")

root_list = c("Potatoes", "carrots", "dry onions", "parsnips", "rutabagas and turnips", "beets")

vegetable_list = c("cabbage", "cauliflowers", "sweet corn", "lettuce", "green and wax beans", "cucumbers and fresh gherkins (all varieties)", "tomatoes", "green peas", "asparagus", "celery", "spinach", "peppers", "garlic", "broccoli", "Brussels sprouts", "leeks", "pumpkins", "French shallots and green onions", "squash and zucchini")

food_crop_list = c("Corn for grain", "Rye, all", "Oats", "Triticale", "Wheat, all", "Beans, all dry (white and coloured)", "Chick peas", "Lentils", "Soybeans", "Peas, dry", "Canola (rapeseed)", "Sunflower seed", "Potatoes", "carrots", "dry onions", "parsnips", "rutabagas and turnips", "beets", "cabbage", "cauliflowers", "sweet corn", "lettuce", "green and wax beans", "cucumbers and fresh gherkins (all varieties)", "tomatoes", "green peas", "asparagus", "celery", "spinach", "peppers", "broccoli", "Brussels sprouts", "leeks", "pumpkins", "French shallots and green onions", "squash and zucchini", "apples", "blueberries", "grapes", "peaches", "pears", "plums and prune plums", "raspberries", "strawberries", "nectarines", "cranberries")

all_crop_list = c("Corn for grain", "Rye, all", "Oats", "Triticale", "Wheat, all", "Beans, all dry (white and coloured)", "Chick peas", "Lentils", "Soybeans", "Peas, dry", "Canola (rapeseed)", "Sunflower seed", "Potatoes", "carrots", "dry onions", "parsnips", "rutabagas and turnips", "beets", "cabbage", "cauliflowers", "sweet corn", "lettuce", "green and wax beans", "cucumbers and fresh gherkins (all varieties)", "tomatoes", "green peas", "asparagus", "celery", "spinach", "peppers", "garlic", "broccoli", "Brussels sprouts", "leeks", "pumpkins", "French shallots and green onions", "squash and zucchini", "apples", "blueberries", "grapes", "peaches", "pears", "plums and prune plums", "raspberries", "strawberries", "nectarines", "sour cherries", "sweet cherries", "cranberries", "Barley", "Corn for silage", "Faba beans", "Sugar beets", "Tame hay")

#notes 
# canary seed not included in feed or cereals, primarily used for pet food?
# flax seed used for clothing/oil?
```

```{r crop_data, echo=FALSE, message = FALSE}

#Field Crops
field_crop_survey <- read_csv("Data/food/food_production/crop/field_crop_survey.csv", skip = 1)%>%
  rename(StatCan_name = "Type of crop")%>%
  filter(REF_DATE %in% (years))

#Potatoes
potato_survey <- read_csv("Data/food/food_production/crop/potato_survey.csv", skip = 1)%>%
  mutate("StatCan_name" = "Potatoes")%>%
  filter(REF_DATE %in% (years))

#Fruits
fruits_survey <- read_csv("Data/food/food_production/crop/fruit_survey.csv", skip = 1)%>%
  separate(Commodity, sep=' \\[', into=c("name", "number"))%>%
  separate(name, sep='Fresh ', into=c("prefix", "StatCan_name"))%>%
  #NAs "total fresh fruit" and "other fresh fruit nes"
  drop_na(StatCan_name)%>%
  filter(REF_DATE %in% (years))

#Vegetables
vegetables_survey <- read_csv("Data/food/food_production/crop/vegetable_survey.csv", skip = 1)%>%
  separate(Commodity, sep=' \\[', into=c("name", "number"))%>%
  separate(name, sep='Fresh ', into=c("prefix", "StatCan_name"))%>%
  #NAs are from , "total fresh veg", "other fresh veg" etc with no number
  drop_na(StatCan_name)%>%
  filter(REF_DATE %in% (years))

#get crop areas in ha, average over 3 years, and bind together ##
field_crop_area <- field_crop_survey%>% 
  filter(`Harvest disposition` == "Harvested area (hectares)")%>%
  rename("area_ha" = VALUE)%>%
  replace_na(list(area_ha = 0))%>%
  group_by(GEO, StatCan_name)%>%
  summarise(area_ha = mean(area_ha))

potato_area <- potato_survey%>%
  filter(`Area, production and farm value of potatoes` == "Harvested area, potatoes")%>%
  #convert acres to hectares
  mutate(area_ha = VALUE/2.471)%>%
  replace_na(list(area_ha = 0))%>%
  group_by(GEO, StatCan_name)%>%
  summarise(area_ha = mean(area_ha))

fruit_area <- fruits_survey%>%
  filter(Estimates == "Bearing area", UOM == "Hectares")%>%
  rename("area_ha" = VALUE)%>%
  replace_na(list(area_ha = 0))%>%
  select(StatCan_name, GEO, area_ha)%>%
  group_by(GEO, StatCan_name)%>%
  summarise(area_ha = mean(area_ha))

vegetable_area <- vegetables_survey%>%
  filter(Estimates == "Area harvested (hectares)")%>%
  rename("area_ha" = VALUE)%>%
  replace_na(list(area_ha = 0))%>%
  select(StatCan_name, GEO, area_ha)%>%
  group_by(GEO, StatCan_name)%>%
  summarise(area_ha = mean(area_ha))

crop_area <- bind_rows(field_crop_area, potato_area, fruit_area, vegetable_area)%>%
  filter(StatCan_name %in% all_crop_list,
         GEO %in% c("Alberta", "British Columbia", "Saskatchewan", "Manitoba", "Ontario", "Quebec", "Prince Edward Island", "Nova Scotia", "Newfoundland and Labrador", "New Brunswick"))%>%
  filter(area_ha > 100)

#get crop production in kg, average over 3 years, and bind together
field_crop_prod <- field_crop_survey %>% 
  filter(`Harvest disposition` == "Production (metric tonnes)")%>%
  mutate(yield_kg = VALUE*1000)%>%
  replace_na(list(yield_kg = 0))%>%
  select(StatCan_name, GEO, yield_kg)%>%
  group_by(GEO, StatCan_name)%>%
  summarise(yield_kg = mean(yield_kg))

potato_prod <- potato_survey%>%
  filter(`Area, production and farm value of potatoes` == "Production, potatoes")%>%
  #convert hundredweight * 1000 to kg
  mutate(yield_kg = VALUE*50.8*1000)%>%
  replace_na(list(yield_kg = 0))%>%
  select(StatCan_name, GEO, yield_kg)%>%
  group_by(GEO, StatCan_name)%>%
  summarise(yield_kg = mean(yield_kg))

fruit_prod <- fruits_survey%>%
  filter(Estimates == "Marketed production", UOM == "Metric tonnes")%>%
  mutate(yield_kg = VALUE*1000)%>%
  replace_na(list(yield_kg = 0))%>%
  select(StatCan_name, GEO, yield_kg)%>%
  group_by(GEO, StatCan_name)%>%
  summarise(yield_kg = mean(yield_kg))

vegetable_prod <- vegetables_survey%>%
  filter(Estimates == "Marketed production (metric tonnes)")%>%
  mutate(yield_kg = VALUE*1000)%>%
  replace_na(list(yield_kg = 0))%>%
  select(StatCan_name, GEO, yield_kg)%>%
  group_by(GEO, StatCan_name)%>%
  summarise(yield_kg = mean(yield_kg))

crop_prod <- bind_rows(field_crop_prod, potato_prod, fruit_prod, vegetable_prod)%>%
  filter(StatCan_name %in% all_crop_list,
         GEO %in% c("Alberta", "British Columbia", "Saskatchewan", "Manitoba", "Ontario", "Quebec", "Prince Edward Island", "Nova Scotia", "Newfoundland and Labrador", "New Brunswick"))%>%
  filter(yield_kg > 1000)
```

```{r Fertilizer, echo=FALSE, message = FALSE}
#Fertilizer Sales N
N_fert_sales <- read_csv("Data/food/fertilizer/fertilizer_shipments.csv", skip = 1)%>%
  separate(`REF_DATE`, sep="/", into=c("REF_DATE", "month"))%>%
  filter(`Fertilizer nutrient content` == "Nitrogen",
         Period == "July to June",
         #get whole year, intead of just growing season
         REF_DATE %in% (years))%>%
  #BC missing a value for 2018, used average of previous two years
  replace_na(list(VALUE = 24.5))%>%
  group_by(GEO, `Fertilizer nutrient content`, UOM, SCALAR_FACTOR)%>%
  summarise(quantity = mean(VALUE))%>%
  mutate(sales_N_kg = quantity*1000000)

#Recommended N Application Rates
#added wheat as average of spring and winter (almost the same)
N_recommended_rates <- read_csv("Data/Food/fertilizer/recommended_fertilizer.csv", skip = 3)%>%
  mutate("Canada" = (rowSums(.[2:7])/7))%>%
  gather(GEO, Rate_kg_ha, `British Columbia`:`Canada`)

#Fertilizer N Application adjusted by the recommended rate for each crop type by the ratio of total N sold provincially (kg) to the total N if recommended rates were used
#Note for fertilizer rates and sales data, PEI, NB NFLD and NS were grouped together as the Atlantic Provinces, so the application rate for these provinces was adjusted by this region 
#StatCan crop names were matched to crop categories for recommended fertilization rates from Yang et al
#Tame hay includes alfalfa (0 kg/ha), seeded forage (improved pasture 50kg/ha) and other tame hay (varies). We have applied the tame hay recommended rate. 
N_rec_fert_crop <- mutate(crop_area, key_rec_fert = case_when(StatCan_name %in% vegetable_list ~ "Vegetables",
                                                              StatCan_name %in% c("carrots", "dry onions", "parsnips", "rutabagas and turnips", "beets") ~ "Vegetables",
                                                          StatCan_name %in% c("blueberries", "raspberries", "strawberries", "cranberries") ~ "Berries",
                                                          StatCan_name %in% c("apples", "peaches", "pears", "plums and prune plums", "nectarines", "sour cherries", "sweet cherries") ~ "Tree fruits",
                                                          StatCan_name %in% c("Barley", "Canary seed", "Rye, all", "Triticale") ~ "Other field",
                                                          StatCan_name %in% c("Beans, all dry (white and coloured)", "Chick peas", "Faba beans", "Lentils", "Peas, dry") ~ "Pulses",
                                                          StatCan_name == "Canola (rapeseed)" ~ "Canola",
                                                          StatCan_name == "Flaxseed" ~ "Flax seed",
                                                          StatCan_name == "Sunflower seed" ~ "Sunflower",
                                                          StatCan_name == "Sugar beets" ~ "Sugar beet",
                                                          StatCan_name == "Wheat, all" ~ "Wheat",
                                                          StatCan_name == "grapes" ~ "Grapes",
                                                          StatCan_name == "Tame hay" ~ "Tame hay",
                                                          TRUE ~ StatCan_name),
                          key_prov_fert = case_when(GEO %in% c("Prince Edward Island", "New Brunswick", "Nova Scotia", "Newfoundland and Labrador") ~ "Atlantic provinces",
                                   TRUE ~ GEO))%>%
  left_join(N_recommended_rates, by  = c("key_rec_fert" = "Crop", "key_prov_fert"="GEO"))%>%
  #total *recommended* fertilizer use for a given crop in a province
  mutate(N_rec_crop_kg = area_ha*Rate_kg_ha)

#total *recommended* fertilizer use by province
N_rec_fert_prov <- (N_rec_fert_crop)%>%
  group_by(key_prov_fert)%>%
  summarize(Total_N_rec_prov = sum(N_rec_crop_kg))

N_adjusted_fert <- left_join(N_rec_fert_crop, N_rec_fert_prov)%>%
  left_join(N_fert_sales, by = c("key_prov_fert" = "GEO"))%>%
  #adjusted by sale/recommended ratio
  mutate(N_applied_crop_kg = (N_rec_crop_kg * sales_N_kg / Total_N_rec_prov))%>%
  #calculated the difference between what the total N value should be if recommended rates were being used, and sales-based values
  mutate(Diff_sales_rec = N_applied_crop_kg - N_rec_crop_kg)
```

```{r BNF, echo=FALSE, message = FALSE}
#BNF rates, HI and residues
HI_Nconc_BNF <- read_csv("Data/Food/food_production/HI_Nconc_BNF.csv", skip = 2)

#BNF fixation
#took weighted average for tame hay other/tame hay alfalfa based on Karimi area of crops
N_BNF <- mutate(crop_prod, key = case_when(StatCan_name %in% vegetable_list ~ "Vegetables",
                                                              StatCan_name %in% c("carrots", "dry onions", "parsnips", "rutabagas and turnips", "beets") ~ "Vegetables",
                                                          StatCan_name %in% c("blueberries", "raspberries", "strawberries", "cranberries", "saskatoon berries", "grapes") ~ "Berries and grapes",
                                                          StatCan_name %in% c("peaches", "pears", "plums and prune plums", "nectarines", "sour cherries", "sweet cherries") ~ "Tree fruit",
                                           StatCan_name == "apples" ~ "Apples",
                                                          TRUE ~ StatCan_name))%>%
  left_join(HI_Nconc_BNF, by = c("key" = "Crop"))%>%
  mutate(yield_DM_kg = yield_kg * ((1-(`H20 content (%w/w)`/100))),
         yield_N_kg = yield_DM_kg * (`N conc prod (%DM)`/100),
         residue_DM_kg = case_when(key %in% c("Berries and grapes", "Tree fruit") ~ ((yield_DM_kg / HI) - yield_DM_kg) * 0.1, #takes into account ~10 yr lifespan of trees/shrubs
                                TRUE ~ ((yield_DM_kg / HI) - yield_DM_kg)),
         residue_N_kg = residue_DM_kg * `N conc res (%DM)`/ 100,
         root_DM_kg = `Below Ground Residue (% of DM harvest)`/ 100  * yield_DM_kg,
         root_N_kg = root_DM_kg * (`N conc root (%DM)`/100),
         N_BNF_kg = (yield_N_kg + residue_N_kg + root_N_kg) * (`%BNFA`/100))%>%
  replace_na(list(N_BNF_kg=0))
```

```{r Field loss, echo=FALSE, message = FALSE}

#Yield N concentrations and allocations of products and above ground residues
residue_allocation <- read_csv("Data/Food/food_production/residue_allocation.csv", skip = 1)

#provincial leaching values
leaching <- read_excel("Data/Food/food_production/Leaching.xlsx", range = "A3:V14")%>% 
  select(`...1`, `mean...22`)%>%
  rename("GEO" = `...1`, "leaching loss %N" = `mean...22`)

N_field_loss <- left_join(N_adjusted_fert, N_BNF, by = c("GEO"="GEO", "StatCan_name"="StatCan_name"))%>%
  select(-c(key_prov_fert, "Fertilizer nutrient content", UOM, SCALAR_FACTOR, quantity))%>%
  left_join(residue_allocation, by = c("key" = "Crop"))%>%
  left_join(leaching)%>%
  mutate(residue_to_soil_N_kg = residue_N_kg * `Residue: Soil %`,
         denitrification_N20_kg = (residue_to_soil_N_kg + root_N_kg ) * 0.05,
         leaching = (residue_to_soil_N_kg + root_N_kg) * `leaching loss %N`,
         N_diff_appl_harvest_kg = N_applied_crop_kg + N_BNF_kg - yield_N_kg,  
         N_loss_field_kg = case_when(N_diff_appl_harvest_kg > 0 ~ N_applied_crop_kg + N_BNF_kg - yield_N_kg + denitrification_N20_kg + leaching,
                                     TRUE ~ denitrification_N20_kg + leaching)
         )%>%
  filter(area_ha > 0,  yield_kg > 0)%>% #to get rid of oddness in surveys, e.g. some crops in some provinces have an area but no harvest or vice versa
  select(-c(4, 6:8, key))%>%
  mutate(PNB = yield_N_kg/N_applied_crop_kg)

```

```{r Crop_processing_loss, echo=FALSE, message = FALSE}

#USDA https://www.ers.usda.gov/data-products/food-availability-per-capita-data-system/ 
food_processing_waste <- read_excel("Data/Food/food_loss_USDA.xlsx", skip = 1)

#consumed N content
food_N_cont <-read_csv("Data/Food/food_production/N_cont_food.csv", skip = 2)

  
#Processing loss
N_crop_process <- mutate(N_field_loss, key_process = case_when(StatCan_name %in% cereals_list ~ "Grains",
                                                 StatCan_name %in% oilseed_list ~ "Fats and oils",
                                                 StatCan_name %in% legume_list ~ "Legumes",
                                                 StatCan_name %in% root_list ~ "Vegetables",
                                                 StatCan_name %in% fruit_list ~ "Fruits",
                                                 StatCan_name %in% vegetable_list ~ "Vegetables",
                                                 TRUE ~ StatCan_name))%>%
  left_join(food_processing_waste, by = c("key_process" = "Food Item"))%>%
  mutate(consumed_kg = yield_kg * (1-(`Total weight loss all levels`/100)))%>%
  left_join(food_N_cont)%>%
  mutate(consumed_N_kg = consumed_kg * `%N content` / 100,         
         N_loss_processing_waste_kg = yield_N_kg - consumed_N_kg)%>%
  mutate(`Food group` = case_when(StatCan_name %in% cereals_list ~ "Grains",
                                                 StatCan_name %in% oilseed_list ~ "Oilseeds",
                                                 StatCan_name %in% legume_list ~ "Legumes",
                                                 StatCan_name %in% root_list ~ "Roots",
                                                 StatCan_name %in% fruit_list ~ "Fruits",
                                                 StatCan_name %in% vegetable_list ~ "Vegetables"))
```

```{r VNF_food_crop, echo=FALSE, message = FALSE}
VNF_crop_group_prov <- N_crop_process%>%
  mutate(Total_N_loss_kg = N_loss_field_kg + N_loss_processing_waste_kg,
         `VNF kgN/kg` = (Total_N_loss_kg / consumed_kg),
         `VNF kgN/kgN` = (Total_N_loss_kg / consumed_N_kg))%>%
  group_by(GEO, `Food group`)%>%
  summarise(`VNF kgN/kg` = weighted.mean(`VNF kgN/kg`, yield_kg))%>%
  drop_na()

#Canadian VNFs by yield weighted average (i.e. avg VNFs are most similar to whichever province grows the most of that food)
VNF_crop_group_CAN <- N_crop_process%>%
  mutate(Total_N_loss_kg = N_loss_field_kg + N_loss_processing_waste_kg,
         `VNF kgN/kg` = (Total_N_loss_kg / consumed_kg),
         `VNF kgN/kgN` = (Total_N_loss_kg / consumed_N_kg))%>%
  drop_na(`Food group`)%>% #removes feed crops
  group_by(`Food group`)%>%
  summarise(`VNF kgN/kg weighted` = weighted.mean(`VNF kgN/kg`, yield_kg))%>%
  mutate(GEO = "Canada")%>%
  mutate(`N footprint sector` = "VN from crops")

VNF_crop_group <- bind_rows(VNF_crop_group_prov, VNF_crop_group_CAN)%>%
  mutate(`N footprint sector` = "VN from crops")%>%
  select(GEO, `Food group`, `N footprint sector`, `VNF kgN/kg weighted`, `VNF kgN/kg`)%>%
  mutate(`VNF kgN/kg` = case_when(GEO == "Canada" ~ `VNF kgN/kg weighted`,
                                  TRUE ~ `VNF kgN/kg`))
```

#Animal VNF
```{r VNF_feed, echo=FALSE, message = FALSE}
VNF_feed_prov <- N_crop_process%>%
  filter(StatCan_name %in% feed_list)%>%
  mutate(`VNF kgN/kg` = (N_loss_field_kg / yield_kg),
         `VNF kgN/kgN` = (N_loss_field_kg / yield_N_kg))
#write_csv(VNF_feed, file.path("Data/Results/VNF_feed.csv"))

#Canadian VNFs by production weighted average (i.e. avg VNFs are most similar to whichever province grows the most of that food)
VNF_feed_CAN <- VNF_feed_prov%>%
  group_by(`StatCan_name`)%>%
  summarise(`VNF kgN/kg` = weighted.mean(`VNF kgN/kg`, yield_kg),
            `VNF kgN/kgN` = weighted.mean(`VNF kgN/kgN`, yield_kg))%>%
  drop_na()%>%
  rename(`Crop type` = StatCan_name)

## Graphing ##
ggplot(VNF_feed_CAN, aes(y = `VNF kgN/kg`*1000, x = `Crop type`, fill = `Crop type`)) +
  geom_bar(position="stack", stat="identity") +
  labs(caption = "Virtual nitrogen factors (g N / kg) for feed crops") +
  scale_fill_brewer(palette="Paired")+
  theme_classic()+
  theme(axis.title.y = element_blank(), 
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks = element_blank(),
        panel.grid = element_blank(),
        panel.border = element_blank(),
        plot.caption = element_text(hjust = 0))

#ggsave("Results_Images/VNF_feed_avg.pdf")
```

```{r animal_pop_data, echo=FALSE, message = FALSE}

layer_prod <- read_csv("Data/Food/food_production/animal/eggs_layers.csv", skip=1)%>%
  filter(`Production and disposition` %in% c("Disposition of eggs in shell sold for consumption [116111111]", "Disposition of eggs in shell, leakers and rejects [116111311]", "Average number of layers"))

layer_pop <- layer_prod%>%
  mutate(StatCan_name = case_when(`Production and disposition` == "Average number of layers" ~ "Layers"))%>%
  filter(REF_DATE %in% years,
         StatCan_name == "Layers")%>%
  replace_na(list(VALUE=0))%>%
  group_by(GEO, StatCan_name, UOM, SCALAR_FACTOR)%>%
  summarise(VALUE = mean(VALUE))

#note on chicken numbers: there's no info # of broiler chickens. Have # of layers, and total number slaughtered. To estimate standing broiler population we have taken the number of total chickens slaughtered in a year and divided by 6.2 (Huffman), which assumes the average age to maturity ~60 days to estimate the number of broilers (matches closely with 114 million number from SPCA). 
poultry_prod <- read_csv("Data/Food/food_production/animal/chicken.csv", skip=1)%>%
  as_tibble()%>%
  filter(`Commodity`== "Chicken (including stewing hen)", `Production and disposition`=="Production, total", Estimates == "Birds")%>%
  mutate("StatCan_name" = "Broiler")%>%
  filter(REF_DATE %in% years)%>%
  replace_na(list(VALUE=0))%>%
  group_by(GEO, StatCan_name, UOM, SCALAR_FACTOR)%>%
  summarise(VALUE = mean(VALUE)/6.2)

#adjusted Atlantic provinces by number of broiler farms 2016 census
#standing population != disposition which is total birds slaughtered
broiler_pop <- poultry_prod%>%
  mutate(VALUE = case_when(GEO == "New Brunswick" ~ 53134 * 12/117/6.2,  #atlantic birds * NB farms/ atlantic farms/ slaughter ratio
                           GEO == "Prince Edward Island" ~ 53134 * 12/117/6.2, 
                           GEO == "Nova Scotia" ~ 53134 * 87/117/6.2,
                           GEO == "Newfoundland and Labrador" ~ 53134  * 6/117/6.2,
                           TRUE ~ VALUE))%>%
  select(GEO, StatCan_name, UOM, SCALAR_FACTOR, VALUE)
    
cattle_pop <- read_csv("Data/Food/food_production/animal/cattle.csv", skip=1)%>%
  as_tibble()%>%
  rename("StatCan_name" = "Livestock")%>%
  filter(`Survey date` == "At January 1",
         `Farm type` %in% c("On dairy operations", "On beef operations"),
         StatCan_name %in% c("Dairy cows", "Heifers for dairy replacement", "Beef cows", "Total beef heifers", "Bulls, 1 year and over", "Steers, 1 year and over"),
         REF_DATE %in% years)%>%
  group_by(REF_DATE, GEO, StatCan_name, UOM, SCALAR_FACTOR)%>% #sum animals on beef and dairy operations
  summarise(VALUE = sum(VALUE))%>%
  group_by(GEO, StatCan_name, UOM, SCALAR_FACTOR)%>%
  summarise(VALUE = mean(VALUE)) #average pop over 3 years
#Did not include "Calves, under 1 year"

pork_pop <- read_csv("Data/Food/food_production/animal/hog.csv", skip=1)%>%
  as_tibble()%>% 
  rename("StatCan_name" = "Livestock")%>%
  filter(`Survey date` == "At January 1", 
         StatCan_name %in% c( "Over 81 kilograms", "54 to 80 kilograms", "23 to 53 kilograms", "Boars, 6 months and over", "Sows and gilts, 6 months and over"),
         REF_DATE %in% years)%>% 
  group_by(GEO, StatCan_name, UOM, SCALAR_FACTOR)%>%
  summarise(VALUE = mean(VALUE))%>%
  replace_na(list(VALUE = 0))
#didn't include under 7kg, because piglets feed hard to measure (also not sure how much of the population is slaughtered) 

animal_pop <- bind_rows(cattle_pop, pork_pop, broiler_pop, layer_pop)

```

```{r VN and N per kg feed, echo=FALSE, message = FALSE}
#note from above: tame hay includes alfalfa mix, seeded pasture, and other tame hay
#tame hay from Sheppard is unweighted average of tame hay, tame pasture and native pasture (so roughly the same)
VNF_feed <- VNF_feed_CAN%>%
  select(`Crop type`, "VNF kgN/kg")%>%
  pivot_wider(names_from =`Crop type`, values_from = "VNF kgN/kg")%>%
  mutate(feed_VN = "feed VN kgN/kg")

N_cont_feed <- HI_Nconc_BNF%>%   #from @Karimi2020
  select(Crop, `N conc prod (%DM)`)%>%
  pivot_wider(names_from = Crop, values_from = `N conc prod (%DM)`)%>%
  mutate(feed_N = "feed N conc DMI")
  
VN_N_feed <- read_excel("Data/Food/food_production/feed_ratios.xlsx", skip = 1)%>%
  as_tibble()%>%
  pivot_longer(cols=3:10, names_to = "Region", values_to = "Fraction")%>%
  mutate(feed_VN = "feed VN kgN/kg", feed_N = "feed N conc DMI")%>%
  left_join(VNF_feed)%>%
  #adjust StatCan feedcrops to match Sheppards categories (not quite the same)
  mutate(feed_group_VNF_kgN_kg = case_when(Region == "%Grain east" ~ (`Barley` + `Corn for silage` + `Soybeans`)/3,
                                    Region == "%Grain west" ~ `Barley`,
                                    Region == "%Whole corn east" ~ `Corn for silage`,
                                    Region == "%Whole corn west" ~ `Corn for silage`,
                                    Region == "%Straw/Hay east" ~ (`Wheat, all` + `Barley`)/2,
                                    Region == "%Straw/Hay west" ~ (`Wheat, all` + `Barley`)/2,
                                    Region == "%Forage east" ~ `Tame hay`/2, #assume natural pasture has no VNF
                                    Region == "%Forage west" ~ `Tame hay`/2,
                                    TRUE ~ 0))%>%
  select(1:4, 6, 12)%>%
  left_join(N_cont_feed)%>%
  mutate(feed_group_N_conc_DMI = case_when(Region == "%Grain east" ~ (`Barley` + `Corn for silage` + `Soybeans`)/3,
                                   Region == "%Grain west" ~ `Barley`,
                                   Region == "%Whole corn east" ~ `Corn for silage`,
                                   Region == "%Whole corn west" ~ `Corn for silage`,
                                   Region == "%Straw/Hay east" ~ (`Wheat, all` + `Wheat, all` + `Barley`)/3,
                                   Region == "%Straw/Hay west" ~ (`Wheat, all` + `Barley`)/2,
                                   Region == "%Forage east" ~ (`Tame hay` + `Pasture (nat)`)/2,
                                   Region == "%Forage west" ~ (`Tame hay` + `Pasture (nat)`)/2,
                                   TRUE ~ `Pasture (nat)`))%>%
  select(1:4, 6, 39)
```

```{r N_feed, echo=FALSE, message = FALSE}
N_feed <- animal_pop%>%
  #match StatCanName to Sheppard's feed groups
  mutate(key_feed = case_when(StatCan_name == "54 to 80 kilograms" ~ "Grower",
                              StatCan_name == "Over 81 kilograms" ~ "Grower",
                              StatCan_name == "23 to 53 kilograms" ~ "Grower",
                              StatCan_name == "7 to 22 kilograms" ~ "Grower",
                              StatCan_name == "Beef cows" ~ "Beef cow",
                              StatCan_name == "Boars, 6 months and over"~ "Boar",
                              StatCan_name == "Bulls, 1 year and over" ~ "Beef bull",
                              StatCan_name == "Calves, under 1 year"~ "Calves",
                              StatCan_name == "Dairy cows"  ~ "Dairy cow",
                              StatCan_name == "Heifers for dairy replacement"~ "Dairy heifer",
                              StatCan_name == "Sows and gilts, 6 months and over"~ "Sow and gilts",
                              StatCan_name == "Steers, 1 year and over" ~ "Beef steer",
                              StatCan_name == "Total beef heifers"~ "Beef heifer",
                              StatCan_name == "Layers"~ "Layer",
                              StatCan_name == "Broiler"~ "Broiler",
                              TRUE ~ StatCan_name))%>%
  left_join(VN_N_feed, by = c("key_feed"="Animal"))%>%
  mutate(VN_feed_kg = case_when((GEO %in% c('British Columbia', 'Alberta', 'Saskatchewan', 'Manitoba')) & (Region %in% c("%Grain west", "%Whole corn west", "%Straw/Hay west", "%Forage west")) ~ VALUE * 1000 * `Feed DMI kg/animal/year` * Fraction * `feed_group_VNF_kgN_kg`,
                                (GEO %in% c("Ontario", "Quebec", "Nova Scotia", "Prince Edward Island", "New Brunswick", "Newfoundland and Labrador")) & (Region %in% c("%Grain east", "%Whole corn east", "%Straw/Hay east", "%Forage east")) ~ VALUE * 1000 * `Feed DMI kg/animal/year` * Fraction * `feed_group_VNF_kgN_kg`))%>%
  mutate(N_feed_kg = case_when((GEO %in% c('British Columbia', 'Alberta', 'Saskatchewan', 'Manitoba')) & (Region %in% c("%Grain west", "%Whole corn west", "%Straw/Hay west", "%Forage west")) ~ VALUE * 1000 * `Feed DMI kg/animal/year` * Fraction * feed_group_N_conc_DMI / 100,
                                (GEO %in% c("Ontario", "Quebec", "Nova Scotia", "Prince Edward Island", "New Brunswick", "Newfoundland and Labrador")) & (Region %in% c("%Grain east", "%Whole corn east", "%Straw/Hay east", "%Forage east")) ~ VALUE * 1000 * `Feed DMI kg/animal/year` * Fraction * feed_group_N_conc_DMI / 100))%>%
  replace_na(list(VN_feed_kg=0, N_feed_kg=0))%>%
  group_by(GEO, StatCan_name, VALUE, UOM, SCALAR_FACTOR, key_feed)%>%
  summarise(VN_feed_kg = sum(VN_feed_kg),
            N_feed_kg = sum(N_feed_kg))%>%
  filter(GEO %in% c('British Columbia', 'Alberta', 'Saskatchewan', 'Manitoba', "Ontario", "Quebec", "Nova Scotia", "Prince Edward Island", "New Brunswick", "Newfoundland and Labrador"))

```

```{r N_manure_production, echo=FALSE, message = FALSE}
slaughter_processing <- read_excel("Data/Food/food_production/animal_processing_conversion.xlsx", skip=1)%>%  
  select(`Animal`,`Fraction Population slaughtered`, `Weight at slaughter (kg/animal)`)
  
animal_N <- read_excel("Data/Food/food_production/animal_N.xlsx", skip =1)

egg_prod <- layer_prod%>%
  filter(`Production and disposition` %in% c("Disposition of eggs in shell sold for consumption [116111111]",
                                             "Disposition of eggs in shell, leakers and rejects [116111311]"),
         REF_DATE %in% years)%>%
  group_by(GEO, `Production and disposition`, UOM, SCALAR_FACTOR)%>%
  summarise(VALUE = mean(VALUE))%>%
  mutate(egg_kg = VALUE * 12 * 1000 * 0.056)%>% #avg large egg weight 56g
  select(GEO, `Production and disposition`, egg_kg)%>%
  pivot_wider(names_from = `Production and disposition`, values_from = egg_kg)%>%
  mutate(Animal="Layers")%>%
  rename("eggs_kg" = `Disposition of eggs in shell sold for consumption [116111111]`, "leakers_kg" = `Disposition of eggs in shell, leakers and rejects [116111311]`)

#NOTE YEAR CHANGES FORMAT AFTER 2000
milk_prod <- read_csv("Data/Food/food_production/animal/milk.csv", skip = 1)%>%
  separate(`REF_DATE`, sep="-", into=c("year", "month"))%>%
  mutate(year = as.double(year))%>%
  group_by(year, GEO, `Dairy distribution`, UOM, SCALAR_FACTOR)%>%
  summarise(VALUE = sum(VALUE))%>%
  filter(year %in% c(17,18,19),
         `Dairy distribution` == "Milk sold off farms, total")%>%
  group_by(GEO, `Dairy distribution`, UOM, SCALAR_FACTOR)%>%
  summarise(VALUE = mean(VALUE))%>%
  mutate(Animal = "Dairy cows",
         milk_kg = VALUE * 1000)%>%
  select(GEO, Animal, milk_kg)

N_manure_prod <- N_feed%>%
  #match StatCanName to Karimi animal N
  mutate(key_animalN = case_when(StatCan_name == "Over 81 kilograms" ~ "Hog",
                                StatCan_name == "54 to 80 kilograms" ~ "Hog",
                                StatCan_name == "23 to 53 kilograms" ~ "Hog",
                                #StatCan_name == "7 to 22 kilograms" ~ "Hog",
                              StatCan_name == "Beef cows" ~ "Cattle",
                              StatCan_name == "Boars, 6 months and over"~ "Hog",
                              StatCan_name == "Bulls, 1 year and over" ~ "Cattle",
                              StatCan_name == "Dairy cows"  ~ "Cattle",
                              StatCan_name == "Heifers for dairy replacement"~ "Cattle",
                              StatCan_name == "Sows and gilts, 6 months and over"~ "Hog",
                              StatCan_name == "Steers, 1 year and over" ~ "Cattle",
                              StatCan_name == "Total beef heifers"~ "Cattle",
                              StatCan_name == "Layers"~ "Chicken",
                              StatCan_name == "Broiler"~ "Chicken"),
         key_product = case_when(StatCan_name == "Over 81 kilograms"  ~ "Pork",
                                    StatCan_name == "54 to 80 kilograms" ~ "Pork",
                                StatCan_name == "23 to 53 kilograms" ~ "Pork",
                               # StatCan_name == "7 to 22 kilograms" ~ "Pork",
                               StatCan_name == "Beef cows" ~ "Beef",
                               StatCan_name == "Boars, 6 months and over" ~ "Pork",
                               StatCan_name == "Broiler" ~ "Chicken",
                               StatCan_name == "Bulls, 1 year and over"  ~ "Beef",
                               StatCan_name == "Heifers for dairy replacement" ~ "Milk",
                               StatCan_name == "Dairy cows" ~ "Milk",
                               StatCan_name == "Layers" ~ "Eggs",
                               StatCan_name == "Sows and gilts, 6 months and over" ~ "Pork",
                               StatCan_name == "Steers, 1 year and over" ~ "Beef",
                               StatCan_name == "Total beef heifers" ~ "Beef",
                               TRUE ~ StatCan_name))%>%
  left_join(animal_N, by = c("key_animalN"="Livestock Type"))%>%
  left_join(milk_prod, by = c("StatCan_name" = "Animal", "GEO"="GEO"))%>%
  left_join(egg_prod, by = c("StatCan_name" = "Animal", "GEO"="GEO"))%>%
  left_join(slaughter_processing, by = c("key_feed" = "Animal"))%>%
  mutate(animals_slaughtered = VALUE * 1000 * `Fraction Population slaughtered`,
         N_animal_content_kg = `Weight at slaughter (kg/animal)` * `% N live weight`,
         yield_kg = case_when(key_product %in% c("Pork", "Beef", "Chicken") ~ animals_slaughtered * `Weight at slaughter (kg/animal)` * `% dressed/live`,
                              key_product == "Milk" ~ milk_kg,
                              key_product == "Eggs" ~ `eggs_kg` + `leakers_kg`),
         yield_N_kg = case_when(key_product %in% c("Pork", "Beef", "Chicken") ~ yield_kg * `% N carcass`,
                                key_product == "Milk" ~ yield_kg * 0.00512,   #USDA protein * 0.16
                                key_product == "Eggs" ~ yield_kg * 0.0208))%>%   #USDA protein * 0.16
          replace_na(list(yield_N_kg=0))%>%  
  mutate(N_manure_prod_kg = case_when(key_product %in% c("Pork", "Beef", "Chicken") ~ N_feed_kg - (N_animal_content_kg * animals_slaughtered),
                              key_product %in% c("Milk", "Eggs") ~ N_feed_kg - yield_N_kg))%>%
  replace_na(list(N_manure_prod_kg = 0, VALUE = 0, yield_kg=0))%>%
  filter((GEO %in% c("Quebec", "Ontario", "Prince Edward Island", "New Brunswick", "Manitoba", "Saskatchewan", "Alberta", "Nova Scotia", "Newfoundland and Labrador", "British Columbia")))

#To compare against national slaughter stats
  #group_by(key_product)%>%
  #summarise(animals_slaughtered = sum(`animals_slaughtered`))
#compared population slaughtered to # Canadian animals slaughtered per year 2018: cattle (-10%) hogs (+4%) chicken (~4%)
  
#to look at manure
  #mutate(`manure/head`= N_manure_prod_kg/VALUE/1000)%>%
  #group_by(StatCan_name)%>%
  #summarise(`N manure/head` = weighted.mean(`manure/head`, VALUE))
#*manure sanity check* compare to Huffman(mine): manure production per head broiler 0.4 (0.21), layer 0.6 (0.73), dairy cow 122 (82), beef cow/bull 78 (71/78), hogs 9.9 (14) 

```

```{r, N manure recycling and loss, echo=FALSE, message = FALSE}
manure_pasture <- read_excel("Data/Food/food_production/manure_pasture.xlsx", skip=1)%>% 
  as_tibble()%>%
  pivot_longer(`British Columbia`:`Newfoundland and Labrador`, names_to = "Province", values_to = "% on pasture")%>%
  select(!(`Kg N / head / yr`))

storage_loss <- read_excel("Data/Food/food_production/manure_storage.xlsx", skip=1)%>%
  as_tibble()%>%
  pivot_longer(`Poultry`:`Others`, names_to = "Animal", values_to = "N% after storage")

N_manure_loss <- N_manure_prod%>%
  mutate(key_pasture = case_when(StatCan_name == "Over 81 kilograms" ~ "Hogs",
                                 StatCan_name == "54 to 80 kilograms" ~ "Hogs",
                                StatCan_name == "23 to 53 kilograms" ~ "Hogs",
                              StatCan_name == "Beef cows" ~ "Beef cattle",
                              StatCan_name == "Boars, 6 months and over"~ "Boars",
                              StatCan_name == "Bulls, 1 year and over" ~ "Bulls",
                              StatCan_name == "Calves, under 1 year"~ "Calves",
                              StatCan_name == "Dairy cows"  ~ "Dairy cows",
                              StatCan_name == "Heifers for dairy replacement"~ "Heifers",
                              StatCan_name == "Sows and gilts, 6 months and over"~ "Sows",
                              StatCan_name == "Steers, 1 year and over" ~ "Steers",
                              StatCan_name == "Total beef heifers"~ "Heifers",
                              StatCan_name == "Layers"~ "Laying hens",
                              StatCan_name == "Broiler" ~ "Broilers",
                              TRUE ~ StatCan_name),
         key_storage = case_when(StatCan_name == "Over 81 kilograms" ~ "Pigs",
                                 StatCan_name == "54 to 80 kilograms" ~ "Pigs",
                                StatCan_name == "23 to 53 kilograms" ~ "Pigs",
                              StatCan_name == "Beef cows" ~ "Cattle",
                              StatCan_name == "Boars, 6 months and over"~ "Pigs",
                              StatCan_name == "Bulls, 1 year and over" ~ "Cattle",
                              StatCan_name == "Calves, under 1 year"~ "Cattle",
                              StatCan_name == "Dairy cows"  ~ "Cattle",
                              StatCan_name == "Heifers for dairy replacement"~ "Cattle",
                              StatCan_name == "Sows and gilts, 6 months and over"~ "Pigs",
                              StatCan_name == "Steers, 1 year and over" ~ "Cattle",
                              StatCan_name == "Total beef heifers"~ "Cattle",
                              StatCan_name == "Layers"~ "Poultry",
                              StatCan_name == "Broiler"~ "Poultry",
                         TRUE ~ StatCan_name))%>%
  left_join(manure_pasture, by = c("key_pasture" = "Animal", "GEO" = "Province"))%>%
  left_join(storage_loss, by = c("key_storage" = "Animal", "GEO" = "Province"))%>%
  left_join(leaching)%>%
  mutate(N_manure_to_soil_kg = ((N_manure_prod_kg*(`% on pasture`/100)) + (N_manure_prod_kg*(1-(`% on pasture`/100))*(`N% after storage`/100))),
         N_manure_loss_storage_kg = N_manure_prod_kg - N_manure_to_soil_kg,
         N_manure_leaching_kg = N_manure_to_soil_kg * `leaching loss %N`,
         `% denitrification` = 0.05,
         N_manure_N20_kg = N_manure_to_soil_kg * `% denitrification`,
         N_manure_N2_kg = N_manure_to_soil_kg * `% denitrification`,
         N_manure_recycled_kg = N_manure_to_soil_kg - N_manure_leaching_kg - N_manure_N20_kg - N_manure_N2_kg)
```

```{r N_process_meat, echo=FALSE, message = FALSE}

# food availability StatsCan doesn't have retail/household losses for meat items so went with USDA values
# meat production sanity check: see manure production

N_animal_process <- N_manure_loss%>%
  left_join(food_processing_waste, by = c("key_product" = "Food Item"))%>%
  left_join(food_N_cont, by = c("key_product"="StatCan_name"))%>%
  mutate(slaughter_loss_N_kg = case_when(key_product %in% c("Pork", "Beef", "Chicken") ~ (N_animal_content_kg * animals_slaughtered) - yield_N_kg,
                                         TRUE ~ 0),
         consumed_kg = yield_kg * (1-(`Total weight loss all levels`/100)),
         consumed_N_kg = consumed_kg * `%N content`/100,
         food_waste_N_kg = yield_N_kg - consumed_N_kg)%>%
  rename("Food group" = "key_product")

  #select(GEO, StatCan_name, "Food group", animals_slaughtered, `Weight at slaughter (kg/animal)`, yield_kg, yield_N_kg, VN_feed_kg, N_manure_loss_storage_kg, N_manure_leaching_kg, N_manure_N20_kg, consumed_kg, consumed_N_kg, food_waste_N_kg)
 # filter(`Food group` %in% c("Eggs", "Chicken"))

```

```{r VNF_animal, echo=FALSE, message = FALSE}
VNF_meat_prov <-  N_animal_process%>%
  group_by(GEO, `Food group`)%>%
  summarise(across(c(VN_feed_kg, N_manure_loss_storage_kg, N_manure_leaching_kg, N_manure_N20_kg, food_waste_N_kg, consumed_kg, slaughter_loss_N_kg, consumed_N_kg), sum))%>%
  mutate(`VNF kgN/kg` = case_when(`Food group` %in% c("Beef", "Pork", "Chicken") ~  (VN_feed_kg + N_manure_loss_storage_kg + N_manure_leaching_kg + N_manure_N20_kg + slaughter_loss_N_kg + slaughter_loss_N_kg + food_waste_N_kg) / consumed_kg,
                                  `Food group` %in% c("Milk", "Eggs") ~ (VN_feed_kg + N_manure_loss_storage_kg + N_manure_leaching_kg + N_manure_N20_kg + food_waste_N_kg) / consumed_kg))%>%
  select(GEO, `Food group`, `VNF kgN/kg`)%>%
  mutate(`N footprint sector` = "VN from meat")%>%
  drop_na()

VNF_meat_CAN <- N_animal_process%>%
  group_by(GEO, `Food group`)%>%
  summarise(across(c(VALUE, VN_feed_kg, N_manure_loss_storage_kg, N_manure_leaching_kg, N_manure_N20_kg, slaughter_loss_N_kg, food_waste_N_kg, consumed_kg, consumed_N_kg), sum))%>%
  mutate(`VNF kgN/kg` = case_when(`Food group` %in% c("Beef", "Pork", "Chicken") ~  (VN_feed_kg + N_manure_loss_storage_kg + N_manure_leaching_kg + N_manure_N20_kg + slaughter_loss_N_kg + slaughter_loss_N_kg + food_waste_N_kg) / consumed_kg,
                                  `Food group` %in% c("Milk", "Eggs") ~ (VN_feed_kg + N_manure_loss_storage_kg + N_manure_leaching_kg + N_manure_N20_kg + food_waste_N_kg) / consumed_kg))%>%
  select(GEO, VALUE, `Food group`, `VNF kgN/kg`)%>%
  group_by(`Food group`)%>%
  drop_na()%>%
  summarise(`VNF kgN/kg weighted` = weighted.mean(`VNF kgN/kg`, VALUE))%>%
  mutate(GEO = "Canada",
         `N footprint sector` = "VN from meat")

VNF_meat <- bind_rows(VNF_meat_prov, VNF_meat_CAN)%>%
  mutate(`VNF kgN/kg` = case_when(GEO == "Canada" ~ `VNF kgN/kg weighted`,
                                  TRUE ~ `VNF kgN/kg`))

#download https://www150.statcan.gc.ca/t1/tbl1/en/cv.action?pid=3210010701 
fish_prod <- read_csv("Data/Food/food_production/animal/aquaculture.csv", skip=1)%>%
  filter(`Finfish and shellfish` == "Total finfish", UOM == "Tonnes",
         REF_DATE %in% years)%>%
  rename("StatCan_name" = "Finfish and shellfish")%>%
  replace_na(list(VALUE = 0))%>%
  group_by(GEO, StatCan_name, UOM, SCALAR_FACTOR)%>% 
  summarise(yeild_kg = mean(VALUE)*1000)%>%
  mutate(feed_kg = yeild_kg * 1.1, #FCR fish
         VNF_feed = feed_kg * 0.7 * 0.0011, #% feed as soy, VNF kg/kg for soy 
         N_manure_kg = yeild_kg * 0.032, #N rate per kg
         N_yield_kg = yeild_kg * 0.025, #N content whole fish
         consumed_kg = yeild_kg * (1-0.41), #USDA fish losses
         N_consumed = consumed_kg * 0.036, # canned salmon N content CCHS
         N_waste_loss = N_yield_kg - N_consumed,   
         `VNF kgN/kg weighted` = (N_manure_kg + N_waste_loss)/consumed_kg,
         `Food group` = "Fish",
         `N footprint sector` = "VN from meat")

VNF_fish <- fish_prod%>%
  filter(GEO == "Canada")%>%
  ungroup()%>%
  select(GEO, `Food group`, `N footprint sector`, `VNF kgN/kg weighted`)

VNF_animal <- bind_rows(VNF_fish, VNF_meat)%>%
  mutate(`VNF kgN/kg` = case_when(GEO == "Canada" ~ `VNF kgN/kg weighted`,
                                  TRUE ~ `VNF kgN/kg`))
```

#Food Consumption
```{r food_consumption, echo=FALSE, message = FALSE}

CCHS_food_names <- read_excel("Data/Food/consumption/cchs-82M0024-E-2015-nu-nci_EDITED.xlsx")%>%
  separate(`BNS name`, sep = "- ", into=c("gram", "BNS_name"))%>%
  separate(`gram`, sep="# ", into=c("#", "BNS_code"))%>%
  separate(BNS_code, sep =":", into=c("BNS_code", "other"))%>% #removes some names, e.g. 1%, 2% for milks but is ok for coding
  select(!c(1,3))

food_consum_g <- read_csv("Data/Food/Consumption/cchs-82M0024-E-2015-nu-nci_F1.csv")%>%
  select(GEO_PRV, BNSD01A:BNSD53B)%>%
  pivot_longer(cols=(BNSD01A:BNSD53B), names_to = c("BNS_code"))%>%
  left_join(CCHS_food_names)%>%
  mutate(food_group = case_when(BNS_name %in% c("Whole Grain/Oats/High Fibre Breakfast Cereals", "Rice", "Corn", "Pasta", "White Breads", "Whole Wheat Breads", "Other Whole Grain Breads", "Breakfast Cereal (Other)", "Cereal/Grains/Flours", "Pancakes/Waffles", "Dry Mixes (Cakes/Muffins/Pancakes)") ~ "Grains",
                                BNS_name %in% c("Milk : Whole",  "Milk : 2%", "Milk : 1%", "Milk : Skim" ) ~ "Milk", 
                                BNS_name %in% c("Cheese: 10% B.F. to 25% B.F.", "Cheese: More than 25% B.F.", "Cheese : Less than 10% B.F.") ~ "Other Dairy",
                                BNS_name %in% c("Egg" ) ~ "Eggs",
                                BNS_name %in% c("Regular Margarine", "Block Margarine", "Vegetable oils") ~ "Oilseeds",
                                BNS_name %in% c("Veal : Lean + Fat/Ground", "Beef : Ground", "Beef : Lean + Fat", "Veal : Lean Only", "Beef : Lean Only") ~ "Beef",
                                BNS_name %in% c("Sausage", "Ham : Cured ", "Bacon", "Pork : Fresh ") ~ "Pork",
                                BNS_name %in% c("Chicken : Meat + Skin", "Chicken : Meat Only" ) ~ "Chicken",
                                BNS_name %in% c("Shellfish", "Fish : Superior or Equal to 6% Total Fat", "Fish : Less than 6% Total Fat") ~ "Fish",
                                BNS_name %in% c("Onion/Green Onions/Leeks/Garlic", "Celery", "Tomatoes", "Peppers : Red/Green", "Cabbage / Kale", "Lettuce/Leafy Greens (Spinach/Mustard Greens)", "Other Veg. (Cucumber/Beet/Turnip)", "Broccoli", "Squashes", "Mushrooms", "Cauliflower") ~ "Vegetables",
                                BNS_name %in% c("Peas/Snow Peas", "Beans", "Foods made with Vegetable Proteins (Tofu)", "Legume")~ "Legumes",
                                BNS_name %in% c("Carrots", "Potato", "Fried/Roasted Potatoes", "Potato Chips") ~ "Roots",
                                BNS_name %in% c("Apple", "Pears", "Citrus Fruit (Oranges/Lemons/Grapefruits)", "Banana", "Grapes/Raisins", "Peaches/Nectarines", "Melons (Canteloup/Honeydew/Watermelon)", "Strawberries", "Other Fruits (Blueberrie/Date/Kiwi/Fruit Salad)", "Cherries", "Pineapple", "Plums/Prunes") ~ "Fruits"))%>%
  left_join(prov_code, by = c("GEO_PRV"="GEO_code"))%>%
  replace_na(list(consumed_protein_g = 0))%>%#for food with no protein content
  filter(value > 0)

# have not included plant milks, # animal fats,  fish yogurts nuts sugars and candies soda, alcohol, fruit drinks coffee tea water lamb baby food spices and baking soda etc 
#cross referenced total protein intake (FSDDPRO) with my estimated sum of food protein +/ - ~ 7%


food_availability <- read_csv("Data/Food/consumption/food_availability.csv", skip = 1)%>%
  filter(`Food categories` == "Food available adjusted for losses",
         REF_DATE %in% years)%>%
  group_by(`Commodity`)%>%
  summarise(`STATSCAN consumed kg/cap/year` = mean(VALUE))%>%
  mutate(food_group = case_when(Commodity %in% c("Apple sauce", "Apples canned", "Apples fresh", "Apples frozen", "Apricots canned", "Apricots fresh", "Artichokes fresh", "Asparagus canned", "Asparagus fresh", "Avocados fresh", "Baked and canned beans", "Bananas fresh", "Blueberries canned", "Blueberries fresh", "Blueberries frozen", "Cherries fresh", "Cherries frozen", "Cranberries fresh", "Grapefruits fresh", "Grapes fresh", "Lemons fresh", "Limes fresh", "Mandarins fresh" , "Melons total fresh", "Nectarines fresh", "Oranges fresh", "Peaches canned", "Peaches fresh", "Pears canned", "Pears fresh", "Pineapples canned", "Pineapples fresh", "Plums total fresh", "Raspberries frozen", "Strawberries canned", "Strawberries fresh",  "Strawberries frozen", "Fruits not specified canned", "Fruits not specified fresh", "Fruits not specified frozen") ~ "Fruits",
                                Commodity %in% c("Broccoli fresh", "Broccoli frozen", "Brussels sprouts fresh", "Brussels sprouts frozen", "Cabbage fresh", "Cauliflower fresh", "Cauliflower frozen", "Celery fresh", "Chinese cabbage fresh", "Cucumbers fresh","Eggplants fresh", "Garlic fresh", "Lettuce fresh", "Mushrooms canned", "Mushrooms fresh", "Peppers fresh", "Pumpkins and squash fresh", "Spinach fresh", "Spinach frozen", "Tomatoes canned", "Tomatoes fresh", "Tomatoes, pulp, paste and puree", "Vegetables not specified canned",  "Vegetables not specified frozen" ) ~ "Vegetables",
                                Commodity %in% c("Beets canned", "Beets fresh", "Carrots canned", "Carrots fresh", "Carrots frozen", "Parsnips fresh", "Leeks fresh", "Onions and shallots fresh", "Potatoes white fresh and processed", "Rutabagas and turnips fresh") ~ "Roots",
                                Commodity %in% c("Corn canned", "Corn flour and meal", "Corn fresh", "Corn frozen", "Oatmeal and rolled oats", "Wheat flour", "Rye flour") ~ "Grains",
                                Commodity %in% c("Beans green and wax canned", "Beans green and wax fresh", "Beans green and wax frozen", "Peas canned", "Peas fresh", "Peas frozen") ~ "Legumes",
                                Commodity %in% c("Beef and veal total, boneless weight") ~ "Beef",
                                Commodity %in% c("Chicken and stewing hen total, boneless weight") ~ "Chicken",
                                Commodity %in% c("Pork, boneless weight") ~ "Pork",
                                Commodity %in% c("Eggs") ~ "Eggs",
                                Commodity %in% c("Other whole milk products", "Partly skimmed milk 1%", "Partly skimmed milk 2%", "Skim milk", "Standard milk 3.25%") ~ "Milk",
                                Commodity %in% c("Margarine", "Salad oils") ~ "Oilseeds",
                                Commodity %in% c("Fresh and frozen sea fish, edible weight","Freshwater fish, edible weight" ) ~ "Fish"))%>%
  group_by(food_group)%>%
  summarise(`STATSCAN consumed kg/cap/year` = sum(`STATSCAN consumed kg/cap/year`))%>%
  drop_na()
 #note have not included juices, various milk products

#adjusting CCHS by national food availability data
food_consum_prov <- food_consum_g%>%
  mutate(consumed_protein = value * `% N`)%>%
  group_by(GEO, food_group)%>%
  summarise(`CCHS consumed kg/cap/year` = mean(value)*365/1000, `mean % N` = mean(`% N`))%>%
  drop_na()

food_consum_CAN <- food_consum_g%>%
  mutate(consumed_protein = value * `% N`)%>%
  group_by(food_group)%>%
  summarise(`CCHS consumed kg/cap/year` = mean(value)*365/1000,
            `mean % N` = mean(`% N`))%>%
  mutate(GEO = "Canada")%>%
  drop_na()

food_consum_CCHS_sum <- food_consum_prov%>%
  group_by(food_group)%>%
  summarise(`CAN CCHS total consumed kg` = sum(`CCHS consumed kg/cap/year`))%>%
  drop_na()

#consumption adjusted by ratio of sum across provinces of statscan/CCHS
food_consum <- bind_rows(food_consum_prov, food_consum_CAN)%>%
  left_join(food_consum_CCHS_sum)%>%
  left_join(food_availability)%>%
  mutate(`adjusted consumed kg/cap/year` = `CCHS consumed kg/cap/year` * `STATSCAN consumed kg/cap/year`* 10 / `CAN CCHS total consumed kg`, 
         `adjusted consumed N kg/cap/year` = `adjusted consumed kg/cap/year` * `mean % N`,
         GEO = case_when(GEO == "Newfoundland Labrador" ~ "Newfoundland and Labrador",
                   TRUE ~ GEO))%>%
  drop_na()%>%
  left_join(prov_pop)%>%
  mutate(`adjusted consumed N kg` = `adjusted consumed N kg/cap/year` * Population, 
         `adjusted consumed kg` = `adjusted consumed kg/cap/year`*Population)
 
#sanity check adults should be getting ~3.2-3.8kg N/year/cap, my results are 3.1-3.4 kg N/year/cap
  #group_by(GEO)%>%
  #summarise("N_consum" = sum(`adjusted consumed N kg/cap/year`))

```

```{r Food consumption stats analysis, echo=FALSE, message = FALSE}

# looking at mean/median consumption of food groups
food_stats <- food_consum_g%>%
  filter(food_group %in% c("Beef", "Milk"))%>%
  group_by(GEO, food_group)%>%
  summarise(
    count = n(),
    mean = mean(value, na.rm = TRUE),
    sd = sd(value, na.rm = TRUE),
    median = median(value, na.rm = TRUE)
  )

# look at normality (It's not normal)
food_group_g <- food_consum_g%>%
  filter(food_group == "Milk",
         value > 0)

ggqqplot(food_group_g$`value`)  

# outliers https://www.r-bloggers.com/2020/01/how-to-remove-outliers-in-r/
# https://www.r-bloggers.com/2017/06/add-p-values-and-significance-levels-to-ggplots

# http://www.sthda.com/english/wiki/kruskal-wallis-test-in-r

#Is there a difference in the mean value consumed between provinces?
kruskal.test(value ~ GEO, data = food_group_g)
# need p-value less 0.05 for significance
#beef:6.051e-07 pork:0.005219 milk:8.092e-10 eggs:2.608e-09 fruits:9.175e-07 vegetables:2.2e-16 

#Which groups are different?
pairwise.wilcox.test(food_group_g$value, food_group_g$GEO,
                 p.adjust.method = "BH")

```

```{r VN_food, echo=FALSE, message = FALSE}

VNF_PROV <- bind_rows(VNF_animal, VNF_crop_group)%>%
  filter(GEO != "Canada")%>%
  select(!`VNF kgN/kg weighted`)

VNF_CAN <- bind_rows(VNF_animal, VNF_crop_group)%>%
  filter(GEO == "Canada")%>%
  select(!c(`VNF kgN/kg`, GEO))

VN_food <- left_join(food_consum, VNF_CAN, by =c("food_group"="Food group"))%>%
  mutate(`N kg/cap/year` = `adjusted consumed kg/cap/year` * `VNF kgN/kg weighted`,
         `N kg/year` = `adjusted consumed kg` * `VNF kgN/kg weighted`)%>%
  select(GEO, food_group, `N footprint sector`, `N kg/cap/year`, `N kg/year`)%>%
  rename(Subsector = food_group)%>%
  drop_na()

```

```{r Sensitivity Analysis VN_food, echo=FALSE, message = FALSE}

USA_VNF <- read_excel("Data/Food/Leach_USA_VNF.xlsx", skip = 1)

VN_sensitivity_PROV <- left_join(food_consum, VNF_CAN, by =c("food_group"="Food group"))%>%
  left_join(USA_VNF, by = c("food_group"="Food Group"))%>%
  left_join(VNF_PROV, by =c("food_group"="Food group", "GEO" = "GEO", "N footprint sector" = "N footprint sector"))%>%
  mutate(`VNF U.S.` = case_when(`food_group` == "Oilseeds" ~ `adjusted consumed kg/cap/year` * `VNF kgN/kg weighted`,
                                TRUE ~ `adjusted consumed kg/cap/year` * `VNF kg N / kg food USA`),
         `VNF CAN weighted` = `adjusted consumed kg/cap/year` * `VNF kgN/kg weighted`,
         `VNF provincial` = case_when(is.na(`VNF kgN/kg`) ~ `adjusted consumed kg/cap/year` * `VNF kgN/kg weighted`,
                                     TRUE ~ `adjusted consumed kg/cap/year` * `VNF kgN/kg`))%>%
  rename(Subsector = food_group)%>%
  select(GEO, `N footprint sector`, Subsector, Population, `VNF U.S.`, `VNF CAN weighted`, `VNF provincial`)%>%
  pivot_longer(cols = starts_with("VN"), names_to = "VNF", values_to = "N kg/cap/year")%>%
  group_by(GEO,`N footprint sector`, Subsector, VNF, Population)%>%
  summarise(`N kg/cap/year` = sum(`N kg/cap/year`))%>%
  filter(GEO !="Canada")%>%
  mutate(`N kg/year` = `N kg/cap/year` * Population)

VN_sensitivity_CAN <- VN_sensitivity_PROV%>%
  group_by(`N footprint sector`, Subsector, VNF)%>%
  summarise(`N kg/cap/year` = weighted.mean(`N kg/cap/year`, Population), `N kg/year` = sum(`N kg/year`))%>%
  mutate(GEO = "Canada")

VN_sensitivity <- VN_sensitivity_PROV%>%
  select(!Population)%>%
  bind_rows(VN_sensitivity_CAN)%>%
  mutate(VNF = factor(VNF, levels = c("VNF provincial", "VNF CAN weighted", "VNF U.S.")))%>%
  mutate(GEO = case_when(GEO == "Prince Edward Island" ~ "PEI",
                   GEO == "Newfoundland and Labrador" ~ "NFLD",
                   TRUE ~ GEO),
         GEO = factor(GEO, levels = c("Canada", "British Columbia", "Alberta", "Saskatchewan", "Manitoba", "Ontario", "Quebec", "New Brunswick", "Nova Scotia", "PEI", "NFLD")),
         GEO = fct_relevel(GEO, "Canada", "British Columbia", "Alberta", "Saskatchewan", "Manitoba", "Ontario", "Quebec", "New Brunswick", "Nova Scotia", "PEI", "NFLD"))
```

#Wastewater
```{r wastewater, echo=FALSE, message = FALSE}
#Population served by municipal wastewater systems by treatment category (Canada/Province)
N_aqueous_wastewater <-  read_csv("Data/Food/wastewater/wastewater.csv", skip = 1)%>%
  rename("year" = "REF_DATE")%>%
  select(year, GEO, `Population by treatment type`, UOM, SCALAR_FACTOR, VALUE)%>%
  filter(`Population by treatment type` != 'All treatment types')%>%
  group_by(year, GEO)%>% 
  #what percent of the population is served by each treatment type
  mutate(percent_pop_covered=VALUE/sum(VALUE))%>%
  ungroup%>%
  # % aqueous N loss as TKN, N03, N02 (N2 and N20 accounted for in next step)
  mutate(`% aqueous N loss` = case_when(`Population by treatment type` == "No treatment" ~ 0.95,
                                  `Population by treatment type` == "Primary treatment" ~ 0.75,
                                  `Population by treatment type` == "Secondary treatment" ~ 0.66,
                                  `Population by treatment type` == "Secondary treatment with additional phosphorus removal" ~ 0.66,
                                  `Population by treatment type` == "Tertiary treatment" ~ 0.30),
         )%>%
  #average treatment over 3 years
  filter(year %in% years)%>%
  group_by(GEO, VALUE, `Population by treatment type`, `% aqueous N loss`)%>%
  summarise(percent_pop_covered = mean(percent_pop_covered))%>%
  #N influent (N from food consumption)
  left_join(food_consum)%>%
  filter(!(GEO %in% c("Canada", "Yukon")))%>% #Canada average currently includes the North, need to remove and re-calculate for comparison with provinces
  #estimate aqueous N loss
  mutate(`N aqueous loss kg/cap/year` = `adjusted consumed N kg/cap/year` * percent_pop_covered * `% aqueous N loss`)%>%
  group_by(GEO)%>%
  summarise(`N aqueous loss kg/cap/year` = sum(`N aqueous loss kg/cap/year`))%>%
  left_join(food_consum)%>%
  mutate(`N inffluent kg/cap/year`= `adjusted consumed N kg/cap/year`)%>%
  group_by(GEO)%>%
  summarise(`N aqueous loss kg/cap/year` = mean(`N aqueous loss kg/cap/year`), `N inffluent kg/cap/year` = sum(`N inffluent kg/cap/year`))%>%
  left_join(prov_pop)%>%
  mutate(`N aqueous loss N kg` = `N aqueous loss kg/cap/year` * Population,
         `N inffluent N kg` = `N inffluent kg/cap/year` * Population)

GHG_wastewater <- read_csv("Data/fossil_fuels/GHG_inventory.csv", skip = 1)%>%
  select(Year, Region, Category, N2O)%>%
  filter(Year %in% years,
         Category == "Wastewater Treatment and Discharge")%>%
  mutate(Category = "Wastewater Treatment",
         `N footprint sector` = "Wastewater Treatment")%>%
  rename("Subsector" = "Category",
         "GEO" = "Region")%>%
  mutate(N_kg = N2O *1000000*14.0067/44.013)%>% #convert kt N20 to kg N
  group_by(GEO, `N footprint sector`, Subsector)%>%
  summarise(`N20 loss N kg` = mean(N_kg))%>%
  mutate(`N2 N kg` = `N20 loss N kg`)%>%
  select(GEO, `N footprint sector`, Subsector, `N20 loss N kg`, `N2 N kg`)%>%
  filter(!(GEO %in% c("Canada", "Nunavut", "Yukon", "Northwest Territories")))

APEI_wastewater <- read_csv("Data/fossil_fuels/APEI_inventory.csv", skip = 1)%>%
  select(Year, Region, Source, Sector, Subsector, `NOX (t)`, `NH3 (t)`)%>%
  mutate(Region = case_when(Region == "AB" ~ "Alberta",
                            Region == "BC" ~ "British Columbia",
                            Region == "MB" ~ "Manitoba",
                            Region == "NB" ~ "New Brunswick",
                            Region == "NL" ~ "Newfoundland and Labrador",
                            Region == "NS" ~ "Nova Scotia",
                            Region == "ON" ~ "Ontario",
                            Region == "PE" ~ "Prince Edward Island",
                            Region == "QC" ~ "Quebec",
                            Region == "SK" ~"Saskatchewan"))%>%
  drop_na(Region)%>%
  rename("GEO" = "Region")%>%
  filter(Subsector %in% c("Incineration and Waste", "Municipal Water and Wastewater Treatment"))%>%
  replace_na(list(`NOX (t)`= 0, `NH3 (t)` = 0))%>%
  mutate(`NH3 NOx loss Nkg/year` = ((`NOX (t)` * 1000 * 14.0067 / 46.0055) + (`NH3 (t)` * 1000 * 14.0067 / 17.031)))%>% #convert NOx weights to N, NOx reported as NO2 equivalent 
  filter(Year %in% years)%>%
  group_by(GEO)%>%
  summarise(`NH3 NOx loss Nkg` = mean(`NH3 NOx loss Nkg/year`))

N_wastewater_PROV <- left_join(N_aqueous_wastewater,APEI_wastewater)%>%
  left_join(GHG_wastewater)%>%
  mutate(`N recyclable kg/year` = `N inffluent N kg` - `N aqueous loss N kg` - `N20 loss N kg` - `N2 N kg`,
         `50% recycled` = `N recyclable kg/year` * 0.5,
         `25% recycled` = `N recyclable kg/year` * 0.75,
         `High` = `N aqueous loss N kg` + `N20 loss N kg` + `NH3 NOx loss Nkg` + `50% recycled`, 
         `Low` = `N aqueous loss N kg` + `N20 loss N kg` + `NH3 NOx loss Nkg` + `25% recycled`)%>%
  pivot_longer(cols = High:Low, names_to = "N recycled", values_to = "N kg/year")%>%
  mutate(`N kg/cap/year` = `N kg/year` / Population)

N_wastewater_CAN <- N_wastewater_PROV%>%
  group_by(`N recycled`)%>%
  summarise(`N kg/cap/year` = weighted.mean(`N kg/cap/year`, Population),
            `N kg/year` = sum(`N kg/year`))%>%
  mutate(`N footprint sector` = "Wastewater Treatment", "Subsector" = "Wastewater Treatment", GEO = "Canada")

N_wastewater_Total <- bind_rows(N_wastewater_PROV, N_wastewater_CAN)%>%
  select(!(Population))%>%
  mutate(GEO = case_when(GEO == "Prince Edward Island" ~ "PEI",
                   GEO == "Newfoundland and Labrador" ~ "NFLD",
                   TRUE ~ GEO),
         `N recycled` = factor(`N recycled`, levels = c("Low", "High")))

```

#Fossil Fuels
```{r Fossil Fuels, echo=FALSE, message = FALSE}

# for source/sector descriptors http://publications.gc.ca/collections/collection_2021/eccc/En81-30-2019-eng.pdf pg15
APEI_energy <- read_csv("Data/fossil_fuels/APEI_inventory.csv", skip = 1)%>%
  select(Year, Region, Source, Sector, Subsector, `NOX (t)`)%>%
  filter(!(is.na(Subsector)))%>% #removes double counts of sectors/sources
  mutate(Region = case_when(Region == "AB" ~ "Alberta",
                            Region == "BC" ~ "British Columbia",
                            Region == "MB" ~ "Manitoba",
                            Region == "NB" ~ "New Brunswick",
                            Region == "NL" ~ "Newfoundland and Labrador",
                            Region == "NS" ~ "Nova Scotia",
                            Region == "ON" ~ "Ontario",
                            Region == "PE" ~ "Prince Edward Island",
                            Region == "QC" ~ "Quebec",
                            Region == "SK" ~"Saskatchewan"))%>%
  mutate(Source = case_when(Source == "Electric Power Generation (Utilities)" ~ "Energy Generation",
                            Sector == "Residential Fuel Combustion" ~ "Energy Generation",
                            Sector == "Commercial and Institutional Fuel Combustion" ~ "Energy Generation",
                            Sector == "Home Firewood Burning" ~ "Energy Generation",
                            Source == "Ore and Mineral Industries" ~ "Other Industry",
                            Source == "Oil and Gas Industry" ~ "Oil and Gas Industry",
                            Source == "Manufacturing" ~ "Other Industry",
                            #(Source == "Transportation and Mobile Equipment" & Sector %in% c("Light-duty Gasoline Trucks", "Light-duty Gasoline Vehicles", "Off-Road Gasoline/LPG/NG Vehicles and Equipment", "Air Transportation")) ~ "Transport",
                            (Source == "Transportation and Mobile Equipment" & Sector != "Marine Transport") ~ "Transport"
                            ))%>% #Incineration and waste captured in Wastewater, paints, dust, and fire sources minimal
  replace_na(list(`NOX (t)`= 0))%>%
  #convert NOx weights to N, NOx reported as NO2 equivalent
  
##MODIFY BASED ON TAKING INTO ACCOUNT OIL EXPORTS###
  mutate(N_kg = case_when(Source == "Oil and Gas Industry" ~ (`NOX (t)` * 1000 * 14.0067 / 46.0055)*0.15,
                          TRUE ~ ((`NOX (t)` * 1000 * 14.0067 / 46.0055))))%>%  
  drop_na(Source, Region)%>%
  filter(Year %in% years)%>%
  group_by(Year, Region, Source)%>%
  summarise(`N kg/year` = sum(N_kg))%>%
  group_by(Region, Source)%>%
  summarise(`N kg/year` = mean(`N kg/year`))

#Canada has only Grand total emissions, so calculated sub categories separately
CAN_APEI <- APEI_energy%>%
  group_by(Source)%>%
  summarise(`N kg/year` = sum(`N kg/year`))%>%
  mutate(Region = "Canada")

APEI_energy <- bind_rows(APEI_energy, CAN_APEI)%>%
  left_join(prov_pop, by = c("Region"="GEO"))%>%
  mutate(`N kg/cap/year` = `N kg/year` / Population)%>%
  select(Region, Source, `N kg/cap/year`,`N kg/year`)

#see GHG executive summary file for explanation of categories http://publications.gc.ca/collections/collection_2020/eccc/En81-4-2018-1-eng.pdf pg 7
GHG_energy <- read_csv("Data/fossil_fuels/GHG_inventory.csv", skip = 1)%>%
  select(Year, Region, Category, N2O)%>%
  mutate(Source = case_when(Category == "Public Electricity and Heat Production" ~ "Energy Generation",
                            Category == "Residential" ~ "Energy Generation",
                            Category == "Commercial and Institutional" ~ "Energy Generation",
                            Category == "Petroleum Refining Industries" ~ "Oil and Gas Industry",
                            Category == "Oil and Gas Extraction" ~ "Oil and Gas Industry",
                            Category == "Mining" ~ "Other Industry",
                            Category == "Manufacturing Industries" ~ "Other Industry",
                            Category == "Construction" ~ "Other Industry",
                            Category == "Domestic Aviation" ~ "Transport",
                            Category == "Road Transportation" ~ "Transport",
                            Category == "Railways" ~ "Transport",
                            Category == "Domestic Navigation" ~ "Transport",
                            Category == "Other Transportation" ~ "Transport",
                            Category == "INDUSTRIAL PROCESSES AND PRODUCT USE" ~ "Other Industry"
                            ))%>%
  drop_na(Source)%>% #could include "Fugitive Sources" "CO2 Transport and Storage"
  replace_na(list(N2O = 0))%>%
  #convert kt N20 to kg N

###MODIFY BASED ON TAKING INTO ACCOUNT OIL EXPORTS###
  mutate(N_kg = case_when(Source == "Oil and Gas Industry" ~ N2O *1000000*14.0067/44.013*0.15,
                          TRUE ~ N2O *1000000*14.0067/44.013))%>%
  filter(Year %in% years)%>%
  group_by(Year, Region, Source)%>%
  summarise(`N kg/year` = sum(N_kg))%>%
  group_by(Region, Source)%>%
  summarise(`N kg/year` = mean(`N kg/year`))%>%
  left_join(prov_pop, by = c("Region"="GEO"))%>%
  mutate(`N kg/cap/year` = `N kg/year` / Population)%>%
  select(Region, Source, `N kg/cap/year`, `N kg/year`)

N_energy <- bind_rows(APEI_energy, GHG_energy)%>%
  filter(Region %in% c("Canada", "Newfoundland and Labrador",	"Prince Edward Island",	"Nova Scotia", "New Brunswick", "Quebec", 	"Ontario",	"Manitoba", "Saskatchewan", "Alberta", "British Columbia"))%>%
  group_by(Region, Source)%>%
  summarise(`N kg/cap/year` = sum(`N kg/cap/year`),
            `N kg/year` = sum(`N kg/year`))%>%
  mutate(`N footprint sector` = "Fossil Fuels")%>%
  rename("GEO"="Region", "Subsector"="Source")%>%
  mutate(GEO = case_when(GEO == "Prince Edward Island" ~ "PEI",
                   GEO == "Newfoundland and Labrador" ~ "NFLD",
                   TRUE ~ GEO),
         GEO = factor(GEO, levels = c("Canada", "British Columbia", "Alberta", "Saskatchewan", "Manitoba", "Ontario", "Quebec", "New Brunswick", "Nova Scotia", "PEI", "NFLD")),
         GEO = fct_relevel(GEO, "Canada", "British Columbia", "Alberta", "Saskatchewan", "Manitoba", "Ontario", "Quebec", "New Brunswick", "Nova Scotia", "PEI", "NFLD"))

```

#Total N footprint
```{r N footprints, echo=FALSE, message = FALSE}
N_footprint <- bind_rows(N_wastewater_Total, N_energy)%>%
  bind_rows(VN_sensitivity)%>%
#choose which version you want
  filter(`N recycled` == "Low" | is.na(`N recycled`))%>%
  filter(`VNF` == "VNF CAN weighted"| is.na(`VNF`))%>%
  mutate(`N footprint sector` = factor(`N footprint sector`, levels = c("VN from crops", "VN from meat", "Wastewater Treatment", "Fossil Fuels")),
         `N footprint sector` = fct_relevel(`N footprint sector`, "VN from crops", "VN from meat", "Wastewater Treatment", "Fossil Fuels"),
         Subsector = factor(Subsector, levels = c("Fruits", "Vegetables", "Grains", "Roots", "Legumes", "Oilseeds", "Milk", "Eggs", "Fish", "Chicken", "Pork", "Beef",          
"Wastewater Treatment", "Energy Generation", "Oil and Gas Industry", "Other Industry", "Transport")),
         Subsector = fct_relevel(Subsector, "Fruits", "Vegetables", "Grains", "Roots", "Legumes", "Oilseeds", "Milk", "Eggs", "Fish", "Chicken", "Pork", "Beef",      "Wastewater Treatment", "Energy Generation", "Oil and Gas Industry", "Other Industry", "Transport"))%>%
  group_by(GEO, `N footprint sector`, Subsector)%>%
  summarise(`N kg/cap/year` = sum(`N kg/cap/year`), `N kg/year` = sum(`N kg/year`))

#write_csv(N_footprint,"Results_Images/N_footprint.csv")

```

# Results and Images
```{r VNF food crop graph, echo=FALSE, message = FALSE}

VNF_graph <- bind_rows(VNF_meat, VNF_crop_group)%>%
   mutate(GEO = case_when(GEO == "Prince Edward Island" ~ "PEI",
                         GEO == "Newfoundland and Labrador" ~ "NFLD",
                         TRUE ~ GEO))%>%
  select(GEO, `Food group`, `N footprint sector`, `VNF kgN/kg weighted`, `VNF kgN/kg`)%>%
  mutate(`VNF kgN/kg` = case_when(GEO == "Canada" ~ `VNF kgN/kg weighted`,
                                  TRUE ~ `VNF kgN/kg`),
         GEO = factor(GEO, levels = c("Canada", "British Columbia", "Alberta", "Saskatchewan", "Manitoba", "Ontario", "Quebec", "New Brunswick", "Nova Scotia", "PEI", "NFLD")))

USA <- USA_VNF%>%
  rename(`VNF kgN/kg` = `VNF kg N / kg food USA`, "Food group" = "Food Group")%>%
  filter(`Food group` != "Fish")

ggplot(VNF_graph, aes(fill = `GEO`, y = `VNF kgN/kg`*1000, x = `GEO`))+
  geom_bar(position="stack", stat="identity") +
  facet_wrap(~factor(`Food group`, levels=c("Roots", "Milk", "Grains", "Legumes", "Fruits", "Vegetables", "Oilseeds", "Eggs", "Chicken", "Pork", "Beef")), scales = "free_x")+
  geom_hline(aes(yintercept = (`VNF kgN/kg` * 1000)), USA)+
  coord_flip()+
  scale_fill_brewer(palette="Paired")+
  theme_classic()+
  theme(axis.title.y = element_blank(), 
        axis.title.x = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "none",
        axis.text.x = element_text(size = 11, angle = 90, hjust = 1, vjust = 0.25),
        axis.text.y = element_text(size = 12),
        strip.text = element_text(size = 12),
        panel.grid = element_blank(),
        panel.border = element_blank(),
        plot.caption = element_text(hjust = 0))

#ggsave("Results_Images/fig_5_VNF_graph.pdf")  


```

```{r Total N footprint graph, echo=FALSE, message = FALSE}

total_graph <- ggplot(subset(N_footprint, GEO != "Canada"), aes(fill = `N footprint sector`, y = `N kg/year`/1000000, x = reorder(GEO, - `N kg/year`)))+
  geom_bar(stat="identity") +
  scale_fill_brewer(palette="Paired")+
  labs(caption = "Total provincial N footprint (Gg/year)")+
  coord_flip()+
  theme_classic()+
  theme(
    axis.text.x = element_text(size=8, angle = 90, hjust = 1, vjust = 0.5),
    axis.text.y = element_text(size=8),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.ticks = element_blank(),
    plot.caption = element_text(hjust = 0))

sector_graph <- ggplot(N_footprint, aes(fill = `N footprint sector`, y = `N kg/cap/year`, x = reorder(GEO, - `N kg/cap/year`)))+
  geom_bar(stat="identity") +
  scale_fill_brewer(palette="Paired")+
  labs(caption = "By sector (N kg/cap/year)")+
  scale_x_discrete()+
  coord_flip()+
  theme_classic()+
  theme(
    axis.text.x = element_text(size=8, angle = 90, hjust = 1, vjust = 0.5),
    axis.text.y = element_text(size=8),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.ticks = element_blank(),
    plot.caption = element_text(hjust = 0))

sector_percent_graph <- ggplot(N_footprint, aes(fill = `N footprint sector`, y = `N kg/cap/year`, x = reorder(GEO, - `N kg/cap/year`)))+
  geom_bar(position = "fill", stat="identity") +
  scale_fill_brewer(palette="Paired")+
  labs(caption = "Sector contribution, % of total")+
  scale_x_discrete()+
  coord_flip()+
  theme_classic()+
  theme(
    axis.text.x = element_text(size=8, angle = 90, hjust = 1, vjust = 0.5),
    axis.text.y = element_text(size=8),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.ticks = element_blank(),
    plot.caption = element_text(hjust = 0))

ggarrange(total_graph, 
          ggarrange(sector_graph, sector_percent_graph,
                    labels = c("B","C"),
                    ncol = 2,
                    legend = "none"),
          nrow = 2,
          labels= "A",
          common.legend = TRUE)

#ggsave("Results_Images/N_print_sectors_graph.pdf")  

```

```{r Graph Provincial footprints per capita by subsector, echo=FALSE, message = FALSE}
colors <- 17
mycolors <- colorRampPalette(brewer.pal(12, "Paired"))(colors)

#subsector_graph <- 
ggplot(N_footprint, aes(fill = `Subsector`, y = `N kg/cap/year`, x = reorder(GEO, -`N kg/cap/year`)))+
  geom_bar(stat="identity") +
  scale_fill_manual(values = mycolors)+
  #scale_fill_brewer(palette="Paired")+
  labs(caption = "By subsector (N kg/cap/year)")+
  coord_flip()+
  theme_classic()+
  theme(
    #legend.position = "none",
    axis.text.x = element_text(size=10, angle = 90, hjust = 1, vjust = 0.5),
    axis.text.y = element_text(size=10),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.ticks = element_blank(),
    plot.caption = element_text(hjust = 0))

#ggsave("Results_Images/N_print_prov_subsectors_cap_graph.pdf")

subsector_percent_graph <- ggplot(N_footprint, aes(fill = `Subsector`, y = `N kg/cap/year`, x = reorder(GEO, -`N kg/cap/year`)))+
  geom_bar(position = "fill", stat="identity") +
  scale_fill_manual(values = mycolors)+
  #scale_fill_brewer(palette="Paired")+
  labs(caption = "Subsector, % of total")+
  coord_flip()+
  guides(fill=guide_legend(ncol=1))+
  theme_classic()+
  theme(
    axis.text.x = element_text(size=10, angle = 90, hjust = 1, vjust = 0.5),
    axis.text.y = element_text(size=10),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.ticks = element_blank(),
    plot.caption = element_text(hjust = 0))

ggarrange(subsector_graph, subsector_percent_graph,
                    labels = c("A","B"),
                    ncol = 2,
                    common.legend = TRUE)

#ggsave("Results_Images/N_print_subsectors_graph.pdf", width = 10)  

```

```{r Wastewater graph, echo=FALSE, message = FALSE}
ggplot(N_wastewater_Total, aes(fill = `N recycled`, y = `N kg/cap/year`, x = `N recycled`))+
  geom_bar(stat="identity") + 
  facet_wrap(~factor(`GEO`, levels=c("Canada", "British Columbia", "Alberta", "Saskatchewan", "Manitoba", "Ontario", "Quebec", "New Brunswick", "Nova Scotia", "PEI", "NFLD")), scales = "free")+
  coord_flip()+
  labs(caption ="Canadian wastewater N footprint using high (50%) and low (25%) recycling assumptions (N kg/cap/year)")+
  scale_fill_brewer(palette="Blues")+
  theme_classic()+
  theme(strip.text.x = element_text(size = 12),
        legend.position = "none",
        axis.text.x = element_text(size=12, angle = 90, hjust = 1, vjust = 0.5),
        axis.text.y = element_text(size=12),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.ticks = element_blank(),
    plot.caption = element_text(hjust = 0))

#ggsave("Results_Images/fig_7_wastewater_sensitivity_graph.pdf", width = 10)
```

```{r Wastewater graph, echo=FALSE, message = FALSE}
ggplot(VN_sensitivity, aes(fill = `N footprint sector`, y = `N kg/cap/year`, x = `VNF`))+
  geom_bar(stat="identity") + 
  facet_wrap(~factor(GEO))+
  labs(caption = "Canadian food N footprint using different VNFs (N kg/cap/year)")+
  coord_flip()+
  scale_fill_brewer(palette="Reds")+
  theme_classic()+
  theme(strip.text = element_text(size = 12),
        legend.text=element_text(size=12),
        legend.title = element_text(size=12),
    axis.text.x = element_text(size=12, angle = 90, hjust = 1, vjust = 0.5),
    axis.text.y = element_text(size=12),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.ticks = element_blank(),
    plot.caption = element_text(hjust = 0))

#ggsave("Results_Images/fig_6_VN_sensitivity_graph.pdf", width = 10)
```